cask_args appdir: '/Applications'

tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'
tap 'thoughtbot/formulae'

brew 'awscli'
brew 'bat'
brew 'coreutils'
brew 'direnv'
brew 'eza'
brew 'fish'
brew 'git'
brew 'git-delta'
brew 'hub'
brew 'jq'
brew 'mise'
brew 'neovim'
brew 'rcm'
brew 'rg'
brew 'rust-analyzer'

cask '1password'
cask 'font-awesome-terminal-fonts'
cask 'font-fontawesome'
cask 'font-hack-nerd-font'
cask 'font-inconsolata'
cask 'font-inconsolata-for-powerline'
cask 'github'
cask 'gpg-suite'
cask 'postico'
cask 'suspicious-package'
cask 'wezterm'
