cask_args appdir: '/Applications'

brew 'awscli'
brew 'bat'
brew 'coreutils'
brew 'direnv'
brew 'eza'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'hub'
brew 'jq'
brew 'just'
brew 'k9s'
brew 'kubernetes-cli'
brew 'lazygit'
brew 'mise'
brew 'neovim'
brew 'rcm'
brew 'rg'
brew 'rust-analyzer'
brew 'starship'

cask '1password'
cask 'font-awesome-terminal-fonts'
cask 'font-fontawesome'
cask 'font-hack-nerd-font'
cask 'font-inconsolata'
cask 'font-inconsolata-for-powerline'
cask 'github'
cask 'gpg-suite'
cask 'postico'
cask 'suspicious-package'
cask 'wezterm'
