#!/bin/sh

#######################################################
# install.sh
# This script sets up a laptop the way that I like it.
# Works on macOS (Homebrew) and Omarchy/Arch (yay).
#######################################################

set -e

DOTFILES="$HOME/.dotfiles"
OS="$(uname -s)"

puts() {
  local fmt="$1"; shift

  printf "\n$fmt\n" "$@"
}

# Move aside anything rcup would otherwise clobber, so nothing is lost. Omarchy
# ships its own nvim (LazyVim), git, lazygit and starship configs.
backup_conflicts() {
  BACKUP="$HOME/.dotfiles-backup/$(date +%Y%m%d-%H%M%S)"

  # rcup links file-by-file, so LazyVim's plugin specs would linger beside ours.
  # Move the whole config — and the plugins/state it installed — aside instead.
  if [ -d "$HOME/.config/nvim" ] && [ ! -L "$HOME/.config/nvim/init.lua" ]; then
    for dir in .config/nvim .local/share/nvim .local/state/nvim .cache/nvim; do
      if [ -e "$HOME/$dir" ]; then
        mkdir -p "$(dirname "$BACKUP/$dir")"
        mv "$HOME/$dir" "$BACKUP/$dir"
      fi
    done
  fi

  env RCRC="$DOTFILES/rcrc" lsrc | while IFS=: read -r dest src; do
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
      rel="${dest#$HOME/}"
      mkdir -p "$(dirname "$BACKUP/$rel")"
      mv "$dest" "$BACKUP/$rel"
    fi
  done

  if [ -d "$BACKUP" ]; then
    puts "Backed up existing configs to %s" "$BACKUP"
  fi
}

case "$OS" in
  Darwin)
    if ! command -v brew >/dev/null; then
      puts "Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    # A fresh Homebrew install isn't on PATH yet in this shell.
    for brew_bin in /opt/homebrew/bin/brew /usr/local/bin/brew; do
      if [ -x "$brew_bin" ]; then
        eval "$("$brew_bin" shellenv)"
        break
      fi
    done

    if ! command -v git >/dev/null; then
      brew install git
    fi
    ;;
  Linux)
    if ! command -v yay >/dev/null; then
      puts "yay not found — this script supports Omarchy/Arch on Linux."
      exit 1
    fi

    if ! command -v git >/dev/null; then
      sudo pacman -S --needed --noconfirm git
    fi
    ;;
esac

if [ ! -d "$DOTFILES" ]; then
  puts "Cloning dotfiles..."
  git clone https://github.com/scrogson/dotfiles "$DOTFILES"
fi

case "$OS" in
  Darwin)
    puts "Updating Homebrew..."
    brew update
    brew bundle --file="$DOTFILES/Brewfile"
    ;;
  Linux)
    puts "Installing packages..."
    yay -S --needed --noconfirm $(sed -e 's/#.*//' "$DOTFILES/Pacfile")
    backup_conflicts
    ;;
esac

puts "Linking dotfiles..."
just --justfile "$DOTFILES/Justfile" --working-directory "$DOTFILES" link

puts "Installing Neovim plugins..."
nvim --headless "+Lazy! sync" +qa

puts "Installing theme watcher..."
just --justfile "$DOTFILES/Justfile" --working-directory "$DOTFILES" theme-watcher

if ! grep -Fxq "$(which fish)" /etc/shells; then
  puts "Adding fish to list of shells"
  echo "$(which fish)" | sudo tee -a /etc/shells
fi

case "$SHELL" in
  */fish) : ;;
  *)
    puts "Changing SHELL to fish..."
      chsh -s "$(which fish)"
    ;;
esac

case "$OS" in
  Darwin)
    # Not run automatically — it rewrites system preferences, so it gets a look
    # first. Generated by scripts/macos/capture.sh on the old Mac and committed.
    if [ -x "$DOTFILES/scripts/macos/restore.sh" ]; then
      puts "macOS settings are ready to apply. Review, then run:"
      puts "  less %s && %s" "$DOTFILES/scripts/macos/restore.sh" "$DOTFILES/scripts/macos/restore.sh"
    fi
    ;;
  Linux)
    # Omarchy launches terminals (Super+Return, etc.) through xdg-terminal-exec.
    # WezTerm's stock desktop entry doesn't say how to pass a command or cwd
    # (it has no -e), so override it with one that does.
    puts "Setting WezTerm as the default terminal..."
    mkdir -p "$HOME/.local/share/applications"
    ln -sf "$DOTFILES/config/omarchy/applications/org.wezfurlong.wezterm.desktop" "$HOME/.local/share/applications/"
    cat > "$HOME/.config/xdg-terminals.list" <<LIST
# Terminal emulator preference order for xdg-terminal-exec
# The first found and valid terminal will be used
org.wezfurlong.wezterm.desktop
LIST
    ;;
esac
