# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[Î»](bold white)"
error_symbol = "[Î»](bold red)"

[aws]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[buf]
disabled = true

[nodejs]
disabled = true

[elixir]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[docker_context]
disabled = true

[kubernetes]
format = '[ðŸ’Ž ($context)](dimmed blue) '
disabled = true

[kubernetes.context_aliases]
".*/production-01$" = "prod"
".*/staging-01$" = "stag"
