#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SNAPSHOT_DIR="$SCRIPT_DIR/snapshot"
RESTORE="$SCRIPT_DIR/restore.sh"

# shellcheck source=settings.sh
source "$SCRIPT_DIR/settings.sh"

echo "==> Exporting domain snapshots to $SNAPSHOT_DIR"
rm -rf "$SNAPSHOT_DIR"
mkdir -p "$SNAPSHOT_DIR"
for domain in "${SNAPSHOT_DOMAINS[@]}"; do
  out="$SNAPSHOT_DIR/${domain}.plist"
  if defaults read "$domain" >/dev/null 2>&1 && defaults export "$domain" "$out" 2>/dev/null; then
    # `defaults export` writes binary; XML is reviewable and diffs in git.
    # `defaults import` reads either, so this costs nothing.
    plutil -convert xml1 "$out" 2>/dev/null || true
    echo "    exported $domain"
  else
    echo "    (skipped $domain — empty or no such domain)"
    rm -f "$out"
  fi
done

# ---- Generate restore.sh ----------------------------------------------------
echo "==> Generating $RESTORE"

# Map our type name to the `defaults write` flag.
defaults_type_flag() {
  case "$1" in
    bool)   echo "-bool" ;;
    int)    echo "-int" ;;
    float)  echo "-float" ;;
    string) echo "-string" ;;
    *) echo "-string" ;;
  esac
}

{
  echo '#!/usr/bin/env bash'
  echo 'set -euo pipefail'
  echo '#'
  echo '# restore.sh — GENERATED by capture.sh. Do not edit by hand; re-run capture.sh.'
  echo '# Applies user-level macOS defaults captured from the old Mac.'
  echo '# Cautious: user-level only, no sudo, idempotent, prints each change.'
  echo '#'
  echo 'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"'
  echo 'SNAP="$DIR/snapshot"'
  echo ''
  echo 'set_default() {  # domain key typeflag value'
  echo '  echo "  set $1 $2 = $4"'
  echo '  defaults write "$1" "$2" "$3" "$4"'
  echo '}'
  echo ''
  echo 'echo "==> Applying captured macOS defaults"'
  echo ''
} > "$RESTORE"

# Emit one line per existing key.
emitted=0
skipped=0
for entry in "${SETTINGS[@]}"; do
  IFS='|' read -r domain key type <<< "$entry"
  if value="$(defaults read "$domain" "$key" 2>/dev/null)"; then
    flag="$(defaults_type_flag "$type")"
    # Normalize bools that `defaults read` prints as 0/1 into true/false.
    if [ "$type" = "bool" ]; then
      case "$value" in
        1|true|TRUE|yes)  value="true" ;;
        0|false|FALSE|no) value="false" ;;
      esac
    fi
    printf 'set_default %q %q %q %q\n' "$domain" "$key" "$flag" "$value" >> "$RESTORE"
    emitted=$((emitted + 1))
  else
    printf '# (unset on source) %s %s\n' "$domain" "$key" >> "$RESTORE"
    skipped=$((skipped + 1))
  fi
done
echo "    scalar settings: $emitted captured, $skipped unset/skipped"

# ---- Keyboard shortcuts (nested; import from snapshot) -----------------------
{
  echo ''
  echo '# --- Keyboard shortcuts (Keyboard > Keyboard Shortcuts) ---'
  echo 'if [ -f "$SNAP/com.apple.symbolichotkeys.plist" ]; then'
  echo '  echo "  import com.apple.symbolichotkeys"'
  echo '  defaults import com.apple.symbolichotkeys "$SNAP/com.apple.symbolichotkeys.plist"'
  echo 'fi'
} >> "$RESTORE"

# Extract NSUserKeyEquivalents (per-app menu overrides) if present.
if defaults read NSGlobalDomain NSUserKeyEquivalents >/dev/null 2>&1; then
  defaults read NSGlobalDomain NSUserKeyEquivalents > "$SNAPSHOT_DIR/$NSGLOBAL_KEYEQUIV_FILE"
  {
    echo 'if [ -f "$SNAP/'"$NSGLOBAL_KEYEQUIV_FILE"'" ]; then'
    echo '  echo "  restore NSUserKeyEquivalents"'
    echo '  defaults write -g NSUserKeyEquivalents "$(cat "$SNAP/'"$NSGLOBAL_KEYEQUIV_FILE"'")"'
    echo 'fi'
  } >> "$RESTORE"
else
  echo '# (no NSUserKeyEquivalents on source)' >> "$RESTORE"
fi

# ---- Apply + manual-steps footer -------------------------------------------
{
  echo ''
  echo '# --- Apply changes without logout ---'
  echo 'echo "==> Restarting Dock, Finder, SystemUIServer"'
  echo 'killall Dock Finder SystemUIServer 2>/dev/null || true'
  echo ''
  echo 'cat <<'"'"'MANUAL'"'"''
  echo ''
  echo '==> Done. These CANNOT be transferred via defaults — set them by hand:'
  echo '    - Touch ID / fingerprints'
  echo '    - Apple ID / iCloud sign-in'
  echo '    - Wi-Fi networks & keychain items'
  echo '    - FileVault'
  echo '    - Anything your IT department locks via a configuration profile'
  echo '      (those writes are silently ignored; the managed value wins)'
  echo 'MANUAL'
} >> "$RESTORE"

chmod +x "$RESTORE"
echo "==> Wrote $RESTORE"
echo "==> Review it, then commit so a new Mac picks it up from the clone:"
echo "      git add scripts/macos/restore.sh scripts/macos/snapshot"
echo "      git commit -m 'Recapture macOS settings'"
echo "==> On the new Mac: cd ~/.dotfiles/scripts/macos && ./restore.sh"
