#!/usr/bin/env bash
set -euo pipefail
#
# restore.sh — GENERATED by capture.sh. Do not edit by hand; re-run capture.sh.
# Applies user-level macOS defaults captured from the old Mac.
# Cautious: user-level only, no sudo, idempotent, prints each change.
#
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SNAP="$DIR/snapshot"

set_default() {  # domain key typeflag value
  echo "  set $1 $2 = $4"
  defaults write "$1" "$2" "$3" "$4"
}

echo "==> Applying captured macOS defaults"

set_default com.apple.dock autohide -bool true
# (unset on source) com.apple.dock autohide-time-modifier
# (unset on source) com.apple.dock autohide-delay
set_default com.apple.dock tilesize -int 16
# (unset on source) com.apple.dock magnification
# (unset on source) com.apple.dock largesize
# (unset on source) com.apple.dock mineffect
# (unset on source) com.apple.dock show-recents
set_default com.apple.dock orientation -string left
# (unset on source) com.apple.dock show-process-indicators
# (unset on source) com.apple.dock launchanim
# (unset on source) com.apple.dock mru-spaces
set_default com.apple.dock wvous-tl-corner -int 10
set_default com.apple.dock wvous-tl-modifier -int 0
# (unset on source) com.apple.dock wvous-tr-corner
# (unset on source) com.apple.dock wvous-tr-modifier
# (unset on source) com.apple.dock wvous-bl-corner
# (unset on source) com.apple.dock wvous-bl-modifier
set_default com.apple.dock wvous-br-corner -int 14
# (unset on source) com.apple.dock wvous-br-modifier
# (unset on source) com.apple.finder ShowPathbar
# (unset on source) com.apple.finder ShowStatusBar
set_default com.apple.finder FXPreferredViewStyle -string icnv
# (unset on source) com.apple.finder _FXShowPosixPathInTitle
# (unset on source) com.apple.finder FXDefaultSearchScope
# (unset on source) com.apple.finder _FXSortFoldersFirst
set_default com.apple.finder ShowHardDrivesOnDesktop -bool false
set_default com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
set_default com.apple.finder ShowRemovableMediaOnDesktop -bool true
# (unset on source) com.apple.finder ShowMountedServersOnDesktop
set_default com.apple.finder FXRemoveOldTrashItems -bool true
set_default NSGlobalDomain AppleShowAllExtensions -bool true
set_default NSGlobalDomain KeyRepeat -int 2
set_default NSGlobalDomain InitialKeyRepeat -int 15
# (unset on source) NSGlobalDomain ApplePressAndHoldEnabled
# (unset on source) NSGlobalDomain AppleKeyboardUIMode
# (unset on source) NSGlobalDomain NSAutomaticSpellingCorrectionEnabled
# (unset on source) NSGlobalDomain NSAutomaticCapitalizationEnabled
# (unset on source) NSGlobalDomain NSAutomaticDashSubstitutionEnabled
# (unset on source) NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled
# (unset on source) NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled
# (unset on source) NSGlobalDomain AppleShowScrollBars
# (unset on source) NSGlobalDomain AppleInterfaceStyle
# (unset on source) NSGlobalDomain NSNavPanelExpandedStateForSaveMode
# (unset on source) NSGlobalDomain PMPrintingExpandedStateForPrint
# (unset on source) NSGlobalDomain AppleICUForce24HourTime
# (unset on source) NSGlobalDomain com.apple.swipescrolldirection
# (unset on source) NSGlobalDomain com.apple.sound.beep.feedback
# (unset on source) NSGlobalDomain com.apple.mouse.tapBehavior
set_default NSGlobalDomain com.apple.trackpad.scaling -float 1
set_default com.apple.AppleMultitouchTrackpad Clicking -bool true
set_default com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool false
set_default com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
set_default com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool false
# (unset on source) com.apple.screencapture location
# (unset on source) com.apple.screencapture type
# (unset on source) com.apple.screencapture disable-shadow
# (unset on source) com.apple.screencapture show-thumbnail
# (unset on source) com.apple.screencapture include-date
# (unset on source) com.apple.menuextra.clock ShowSeconds
set_default com.apple.menuextra.clock ShowDayOfWeek -bool true
set_default com.apple.menuextra.clock ShowDate -int 0
# (unset on source) com.apple.menuextra.clock Show24Hour
# (unset on source) com.apple.screensaver askForPassword
# (unset on source) com.apple.screensaver askForPasswordDelay

# --- Keyboard shortcuts (Keyboard > Keyboard Shortcuts) ---
if [ -f "$SNAP/com.apple.symbolichotkeys.plist" ]; then
  echo "  import com.apple.symbolichotkeys"
  defaults import com.apple.symbolichotkeys "$SNAP/com.apple.symbolichotkeys.plist"
fi
# (no NSUserKeyEquivalents on source)

# --- Apply changes without logout ---
echo "==> Restarting Dock, Finder, SystemUIServer"
killall Dock Finder SystemUIServer 2>/dev/null || true

cat <<'MANUAL'

==> Done. These CANNOT be transferred via defaults — set them by hand:
    - Touch ID / fingerprints
    - Apple ID / iCloud sign-in
    - Wi-Fi networks & keychain items
    - FileVault
    - Anything your IT department locks via a configuration profile
      (those writes are silently ignored; the managed value wins)
MANUAL
