git:
  paging:
    colorArg: always
    pager: delta --paging=never

gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - '#539bf5'
      - bold
    inactiveBorderColor:
      - '#444c56'
    searchingActiveBorderColor:
      - '#e5534b'
      - bold
    optionsTextColor:
      - '#539bf5'
    selectedLineBgColor:
      - '#2d333b'
    selectedRangeBgColor:
      - '#2d333b'
    cherryPickedCommitBgColor:
      - '#2d333b'
    cherryPickedCommitFgColor:
      - '#539bf5'
    unstagedChangesColor:
      - '#e5534b'
    defaultFgColor:
      - '#adbac7'
    markedBaseCommitFgColor:
      - '#539bf5'
    markedBaseCommitBgColor:
      - '#2d333b'